name: Mac Push Build With Existing

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Read Config File
        id: read_config
        run: |
          while IFS=: read -r key value; do
            key=$(echo "$key" | xargs)
            value=$(echo "$value" | xargs)
            echo "$key=$value" >> $GITHUB_ENV
          done < mainConfig.txt
        shell: bash

      - name: Get latest ModSatRunner using version number
        id: download-modsatrunner
        run: |
          version=${{ env.version }}
          artifacts=$(curl -s -H "Authorization: token ${{ secrets.SKEDAI_ACTION_TOKEN }}" "https://api.github.com/repos/proshkin/SkedaiSatRunner/actions/artifacts")
          matchingArtifact=$(echo "$artifacts" | jq -r --arg VERSION "_mac$version" '.artifacts[] | select(.name | endswith($VERSION))')
          artifactId=$(echo "$matchingArtifact" | jq -r '.id')
          
          if [ -z "$artifactId" ]; then
            echo "No matching artifact found for version $version"
            exit 1
          fi

          curl -L -H "Authorization: token ${{ secrets.SKEDAI_ACTION_TOKEN }}" -o artifact.zip "https://api.github.com/repos/proshkin/SkedaiSatRunner/actions/artifacts/$artifactId/zip"
          artifactDir="components"
          mkdir -p $artifactDir
          unzip artifact.zip -d $artifactDir
        shell: bash

      - name: Get latest Authenticator using version number
        id: download-authenticator
        run: |
          version=${{ env.version }}
          artifacts=$(curl -s -H "Authorization: token ${{ secrets.SKEDAI_ACTION_TOKEN }}" "https://api.github.com/repos/proshkin/SkedaiAuthenticator/actions/artifacts")
          matchingArtifact=$(echo "$artifacts" | jq -r --arg VERSION "_mac$version" '.artifacts[] | select(.name | endswith($VERSION))')
          artifactId=$(echo "$matchingArtifact" | jq -r '.id')
          
          if [ -z "$artifactId" ]; then
            echo "No matching artifact found for version $version"
            exit 1
          fi

          curl -L -H "Authorization: token ${{ secrets.SKEDAI_ACTION_TOKEN }}" -o artifact.zip "https://api.github.com/repos/proshkin/SkedaiAuthenticator/actions/artifacts/$artifactId/zip"
          artifactDir="components"
          mkdir -p $artifactDir
          unzip artifact.zip -d $artifactDir
        shell: bash

      - name: Get latest UserServer using version number
        id: download-userserver
        run: |
          version=${{ env.version }}
          artifacts=$(curl -s -H "Authorization: token ${{ secrets.SKEDAI_ACTION_TOKEN }}" "https://api.github.com/repos/proshkin/SkedaiUserServer/actions/artifacts")
          echo "API Response: $artifacts"
          
          matchingArtifact=$(echo "$artifacts" | jq -r --arg VERSION "_mac$version" '.artifacts[] | select(.name | endswith($VERSION))')
          artifactId=$(echo "$matchingArtifact" | jq -r '.id')
          
          if [ -z "$artifactId" ]; then
            echo "No matching artifact found for version $version"
            exit 1
          fi

          curl -L -H "Authorization: token ${{ secrets.SKEDAI_ACTION_TOKEN }}" -o artifact.zip "https://api.github.com/repos/proshkin/SkedaiUserServer/actions/artifacts/$artifactId/zip"
          artifactDir="components"
          mkdir -p $artifactDir
          unzip artifact.zip -d $artifactDir

          exePattern="userServer_mac"
          exeFile=$(find $artifactDir -name "$exePattern" | head -n 1)
          if [ -n "$exeFile" ]; then
            mv "$exeFile" "$artifactDir/userServer_mac"
          else
            echo "No executable file matching the pattern '$exePattern' found in the extracted artifacts."
            exit 1
          fi
        shell: bash

      - name: Move executables to packaging directory
        run: |
          mkdir -p $GITHUB_WORKSPACE/pkgroot/usr/local/bin
          mv components/userServer_mac $GITHUB_WORKSPACE/pkgroot/usr/local/bin/
          mv components/skedaisatrunner $GITHUB_WORKSPACE/pkgroot/usr/local/bin/
          mv components/authenticator $GITHUB_WORKSPACE/pkgroot/usr/local/bin/

      - name: Create plist file for service
        run: |
          mkdir -p $GITHUB_WORKSPACE/pkgroot/Library/LaunchAgents
          plistContent='<?xml version="1.0" encoding="UTF-8"?>\n<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n<plist version="1.0">\n  <dict>\n    <key>Label</key>\n    <string>com.aitkn.skedaiuserserver</string>\n    <key>ProgramArguments</key>\n    <array>\n      <string>/usr/local/bin/userServer_mac</string>\n    </array>\n    <key>RunAtLoad</key>\n    <true/>\n    <key>KeepAlive</key>\n    <true/>\n    <key>StandardErrorPath</key>\n    <string>/usr/local/var/log/userserver.err</string>\n    <key>StandardOutPath</key>\n    <string>/usr/local/var/log/userserver.out</string>\n  </dict>\n</plist>'
          echo -e "$plistContent" > $GITHUB_WORKSPACE/pkgroot/Library/LaunchAgents/com.aitkn.skedaiuserserver.plist

      - name: Create log directory
        run: |
          mkdir -p $GITHUB_WORKSPACE/pkgroot/usr/local/var/log

      - name: Build the installer package
        run: |
          pkgbuild --root $GITHUB_WORKSPACE/pkgroot \
                   --identifier com.aitkn.skedaiuserserver \
                   --version ${{ env.version }} \
                   --install-location / \
                   userServerInstaller.pkg

      - name: Upload installer package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: userServerInstaller
          path: userServerInstaller.pkg
